### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=RustRover

###
GET localhost:8000/


### Categories
POST localhost:8000/api/category
Content-Type: application/json

{
  "name": "cat2"
}


### 
GET localhost:8000/api/category/all



### ingredients with description
POST localhost:8000/api/ingredient
Content-Type: application/json

{
  "name": "ing1",
  "description": "Meine Description",
  "category_id": 1
}

### ingredients without description
POST localhost:8000/api/ingredient
Content-Type: application/json

{
  "name": "ing1",
  "category_id": 1
}

###
GET localhost:8000/api/ingredient/all
