### Categories

### Create category
POST localhost:8000/api/categories
Content-Type: application/json

{
  "name": "cat4"
}

### get all categories
GET localhost:8000/api/categories

### get single category
GET localhost:8000/api/categories/10

### update categoty
PUT localhost:8000/api/categories/10
Content-Type: application/json

{
  "name": "cat_updated"
}

### delete categories
DELETE localhost:8000/api/categories/9




##### Ingredients

### Create ingredient with description
POST localhost:8000/api/ingredients
Content-Type: application/json

{
  "name": "ing1",
  "description": "Meine Description",
  "category_id": 1
}

### create ingredients without description
POST localhost:8000/api/ingredients
Content-Type: application/json

{
  "name": "ing1",
  "category_id": 1
}

### get all ingredients
GET localhost:8000/api/ingredients

### get single ingredient

### update ingredient

### delete ingredient